[package]
name = "cephes"
version = "0.1.0"
authors = ["10x Genomics"]
license-file = "../LICENSE"
edition = "2021"
include = ["src/**/*", "LICENSE", "!**/tests/**/*"]

[dev-dependencies]
approx = "0.4"
