/* automatically generated by rust-bindgen 0.58.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSNE {
    _unused: [u8; 0],
}
extern "C" {
    pub fn init_tsne(
        X: *mut f64,
        N: ::std::os::raw::c_int,
        D: ::std::os::raw::c_int,
        Y: *mut f64,
        no_dims: ::std::os::raw::c_int,
        perplexity: f64,
        theta: f64,
        rand_seed: ::std::os::raw::c_int,
        skip_random_init: bool,
        init: *const f64,
        use_init: bool,
        max_iter: ::std::os::raw::c_int,
        stop_lying_iter: ::std::os::raw::c_int,
        mom_switch_iter: ::std::os::raw::c_int,
    ) -> *mut TSNE;
}
extern "C" {
    pub fn step_tsne_by(tsne: *mut TSNE, step: ::std::os::raw::c_int) -> bool;
}
extern "C" {
    pub fn free_tsne(tsne: *mut TSNE);
}
